"""Kit growth assessment: published reference curve plus per-kit deviation trend.

TWO SEPARATE MODELS, DELIBERATELY
---------------------------------
1. The REFERENCE CURVE is a Gompertz function whose parameters were fitted to
   PUBLISHED population means from Palka et al. (2018). It is loaded from
   ml_models/growth_reference_params.json and never fitted here.

2. The DEVIATION TREND is an ordinary least squares regression of
   (observed - reference) against age, fitted at request time to the owner's
   OWN measurements. It has no training set of any kind.

This split matters. The reference curve is literature; the personal model is
real user data. Neither is learned from generated data, which is the specific
criticism levelled at synthetic medical datasets.

WHY DEVIATION AND NOT WEIGHT
----------------------------
A kit can be permanently lighter than the reference and completely healthy —
the published animals were commercial meat breeds under controlled husbandry.
What matters clinically is whether the gap is WIDENING. Regressing the
deviation isolates exactly that, and makes the slope interpretable on its own:
zero means tracking the reference, whatever the absolute weight.
"""

from __future__ import annotations

import json
from datetime import date
from pathlib import Path

import numpy as np

# Version string for this scoring logic plus the loaded parameter set. Stored
# on every response so a result remains interpretable after the curve is
# refitted. Bump this whenever growth_reference_params.json is regenerated.
MODEL_VERSION = "growth-gompertz-1.0.0"

# Regression is refused below this many points: two points define a line
# exactly and say nothing about trend.
MIN_POINTS_FOR_TREND = 3

# Below this, the fit is shown but explicitly marked provisional.
MIN_POINTS_FOR_CONFIDENCE = 5

# A kit is "falling behind" when its deficit grows faster than this.
#
# Not an arbitrary number. Palka et al. (2018) found battery-housed rabbits
# finished 445 g heavier than box-housed ones at 12 weeks. Spread over the
# 12-week rearing period that is roughly 37 g per week, and it is a documented,
# biologically real divergence rate between two groups of healthy animals. A
# kit diverging at least that fast is departing from its reference at a rate
# the literature treats as significant.
FALLING_BEHIND_SLOPE_G_PER_WEEK = -37.0

# Beyond this age the source data ends and both the curve and its spread are
# extrapolation. Palka et al. weighed to 12 weeks only.
REFERENCE_MAX_WEEKS = 12.0


class GrowthReferenceError(RuntimeError):
    """Raised when the reference parameter file is missing or malformed."""


def _load_reference() -> dict:
    """Load and validate the fitted parameters once, at import.

    Loading at import rather than per request means a corrupt or missing file
    fails loudly at startup instead of intermittently under traffic — the same
    reasoning as loading the illness model's joblib at import.
    """
    path = Path(__file__).resolve().parents[2] / "ml_models" / "growth_reference_params.json"
    if not path.exists():
        raise GrowthReferenceError(
            f"Reference parameters not found at {path}. Run "
            "ai_training/fit_reference_curve.py and copy the JSON into "
            "backend/ml_models/."
        )

    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)

    groups = data.get("groups")
    if not groups:
        raise GrowthReferenceError("Reference file contains no 'groups' key.")

    for name in ("battery", "box"):
        if name not in groups:
            raise GrowthReferenceError(f"Reference file is missing group '{name}'.")
        g = groups[name]
        for key in ("A_g", "b", "k_per_week", "observed_g", "published_sd_g"):
            if key not in g:
                raise GrowthReferenceError(
                    f"Group '{name}' is missing required key '{key}'."
                )

    return data


REFERENCE = _load_reference()

# Ages corresponding to each element of observed_g / published_sd_g. The fit
# script writes birth plus weeks 1..12 in order.
_N_POINTS = len(REFERENCE["groups"]["battery"]["published_sd_g"])
REFERENCE_AGES_WEEKS = np.arange(_N_POINTS, dtype=float)


# Static, reviewable guidance text. NOT generated by any model — the same rule
# applied to TIER_GUIDANCE in the illness service. A person can read every
# string a user might see.
ASSESSMENT_GUIDANCE: dict[str, str] = {
    "unknown": (
        "Not enough measurements yet to show a trend. Weigh this kit weekly; "
        "three weighings will give a first estimate."
    ),
    "on_track": (
        "This kit is growing in line with the published reference for its age."
    ),
    "above_reference": (
        "This kit is heavier than the published reference. That is usually "
        "nothing to worry about — reference animals were commercial meat "
        "breeds and individual rabbits vary."
    ),
    "below_reference": (
        "This kit is lighter than the published reference, but the gap is "
        "steady rather than widening, which suggests it is growing at a "
        "normal rate from a smaller starting point."
    ),
    "falling_behind": (
        "This kit is falling further behind the reference each week. A "
        "widening gap can indicate a feeding problem, competition from "
        "littermates, or illness. Consider contacting a vet."
    ),
}

GROUP_LABELS: dict[str, str] = {
    "battery": "Individually or pair-housed reference",
    "box": "Group-housed reference",
}

SOURCE_CITATION = (
    "Palka, S., Kmiecik, M., Migdal, L., Koziol, K., Otwinowska-Mindur, A. & "
    "Bieniek, J. (2018). Effect of housing system and breed on growth, "
    "slaughter traits and meat quality traits in rabbits. Scientific Annals "
    "of the Polish Society of Animal Production, 14(4), 9-18."
)


def select_reference_group(housing_context: str) -> str:
    """Map a litter's housing context to a published reference group.

    Housing, not breed, selects the curve. Palka et al. found housing
    significantly affected weight from week 6 while breed did not, so keying
    on breed would be keying on the variable their data showed did not matter.

    'unknown' falls back to the individual/battery curve because most pet
    litters are reared in a nest box with the doe rather than in a group pen.
    """
    return "box" if housing_context == "group" else "battery"


def gompertz(age_weeks: float | np.ndarray, A: float, b: float, k: float):
    """Gompertz growth function. Returns predicted weight in grams.

        W(t) = A * exp(-b * exp(-k * t))
    """
    return A * np.exp(-b * np.exp(-k * np.asarray(age_weeks, dtype=float)))


def reference_weight_g(age_weeks: float, group: str) -> float:
    """Expected weight in grams at a given age, from the fitted curve."""
    params = REFERENCE["groups"][group]
    return float(
        gompertz(age_weeks, params["A_g"], params["b"], params["k_per_week"])
    )


def reference_sd_g(age_weeks: float, group: str) -> float:
    """Published standard deviation at a given age, linearly interpolated.

    This is the natural spread of real animals at that age, and it is what
    decides whether a deviation is meaningful. The published SD runs from 8 g
    at birth to 253 g at 12 weeks, so a fixed gram threshold would be far too
    strict early and far too loose late.

    Beyond the source data's 12 weeks the last published SD is held constant.
    That is extrapolation and is flagged to the user rather than hidden.
    """
    sds = np.asarray(REFERENCE["groups"][group]["published_sd_g"], dtype=float)
    clamped = float(np.clip(age_weeks, 0.0, REFERENCE_AGES_WEEKS[-1]))
    return float(np.interp(clamped, REFERENCE_AGES_WEEKS, sds))


def fit_deviation_trend(
    ages_weeks: list[float], deviations_g: list[float]
) -> dict[str, float]:
    """Ordinary least squares of deviation-from-reference against age.

    Fitted to the owner's own measurements at request time. Not cached: this
    is a handful of points and the fit costs microseconds, whereas a cached
    result could silently go stale after an edit.

    R-squared here describes how consistently the kit deviates, not how good
    the reference curve is. A low value with a near-zero slope simply means
    noisy weighings around a stable gap, which is normal.
    """
    x = np.asarray(ages_weeks, dtype=float)
    y = np.asarray(deviations_g, dtype=float)

    slope, intercept = np.polyfit(x, y, 1)

    y_hat = slope * x + intercept
    ss_res = float(np.sum((y - y_hat) ** 2))
    ss_tot = float(np.sum((y - np.mean(y)) ** 2))

    # ss_tot is zero when every deviation is identical. The line fits
    # perfectly, but R-squared is undefined rather than 1.0, so report 0.0 and
    # let the slope speak.
    r_squared = 1.0 - ss_res / ss_tot if ss_tot > 0 else 0.0

    return {
        "slope_g_per_week": float(slope),
        "intercept_g": float(intercept),
        "r_squared": float(r_squared),
    }


def _classify(
    latest_deviation_g: float,
    latest_sd_g: float,
    slope_g_per_week: float | None,
) -> str:
    """Decide the assessment label.

    Order matters. A widening gap is checked first because it is the pattern
    worth acting on, and a kit can be inside the normal band today while
    dropping out of it steadily.
    """
    if slope_g_per_week is not None and slope_g_per_week <= FALLING_BEHIND_SLOPE_G_PER_WEEK:
        return "falling_behind"

    # One published SD is the band of normal variation at that age.
    if abs(latest_deviation_g) <= latest_sd_g:
        return "on_track"

    return "above_reference" if latest_deviation_g > 0 else "below_reference"


def analyse_growth(
    *,
    kit_id,
    identifier: str,
    kindling_date: date,
    housing_context: str,
    weights: list[tuple[date, int]],
) -> dict:
    """Build the full growth assessment for one kit.

    Takes plain values rather than ORM objects so it can be unit tested with
    no database. The route layer does the querying and ownership filtering.

    `weights` is a list of (measured_on, weight_g) pairs. Order does not
    matter; they are sorted here.
    """
    group = select_reference_group(housing_context)
    params = REFERENCE["groups"][group]

    ordered = sorted(weights, key=lambda w: w[0])

    points: list[dict] = []
    ages_weeks: list[float] = []
    deviations_g: list[float] = []
    beyond_reference_range = False

    for measured_on, weight_g in ordered:
        age_days = (measured_on - kindling_date).days
        if age_days < 0:
            # Defensive: the route rejects these on write, but a kindling_date
            # edited later can strand existing rows before the birth date.
            raise ValueError(
                f"Weight dated {measured_on} precedes the kindling date "
                f"{kindling_date}."
            )

        age_weeks = age_days / 7.0
        if age_weeks > REFERENCE_MAX_WEEKS:
            beyond_reference_range = True

        ref = reference_weight_g(age_weeks, group)
        deviation = float(weight_g) - ref

        points.append(
            {
                "measured_on": measured_on,
                "age_days": age_days,
                "age_weeks": round(age_weeks, 2),
                "weight_g": weight_g,
                "reference_g": round(ref, 1),
                "deviation_g": round(deviation, 1),
                "deviation_pct": round(100.0 * deviation / ref, 1) if ref > 0 else 0.0,
            }
        )
        ages_weeks.append(age_weeks)
        deviations_g.append(deviation)

    n = len(points)

    if n == 0:
        return {
            "kit_id": kit_id,
            "identifier": identifier,
            "kindling_date": kindling_date,
            "latest_age_days": None,
            "reference_group": group,
            "reference_label": GROUP_LABELS[group],
            "model_version": MODEL_VERSION,
            "points": [],
            "trend": None,
            "confidence_state": "insufficient_data",
            "assessment": "unknown",
            "message": ASSESSMENT_GUIDANCE["unknown"],
        }

    trend = None
    slope = None
    if n >= MIN_POINTS_FOR_TREND:
        trend = fit_deviation_trend(ages_weeks, deviations_g)
        trend["n_points"] = n
        slope = trend["slope_g_per_week"]

    if n < MIN_POINTS_FOR_TREND:
        confidence_state = "insufficient_data"
    elif n < MIN_POINTS_FOR_CONFIDENCE:
        confidence_state = "provisional"
    else:
        confidence_state = "established"

    latest = points[-1]
    latest_sd = reference_sd_g(latest["age_weeks"], group)

    if trend is None:
        assessment = "unknown"
    else:
        assessment = _classify(latest["deviation_g"], latest_sd, slope)

    message = ASSESSMENT_GUIDANCE[assessment]

    if confidence_state == "provisional":
        message += (
            " This is based on only a few weighings, so treat it as "
            "provisional until you have at least five."
        )

    if beyond_reference_range:
        message += (
            " Some measurements are past 12 weeks, where the published "
            "reference data ends, so the comparison there is an estimate."
        )

    return {
        "kit_id": kit_id,
        "identifier": identifier,
        "kindling_date": kindling_date,
        "latest_age_days": latest["age_days"],
        "reference_group": group,
        "reference_label": GROUP_LABELS[group],
        "model_version": MODEL_VERSION,
        "points": points,
        "trend": trend,
        "confidence_state": confidence_state,
        "assessment": assessment,
        "message": message,
    }


def build_reference_curve(group: str, max_weeks: float = 12.0, step: float = 0.5) -> dict:
    """Return the reference curve as plottable points.

    Served to the client so the chart can be drawn without the app hardcoding
    any parameters. Refitting the curve then updates every device without a
    store release — the same reasoning as the server-owned symptom catalogue.
    """
    if group not in REFERENCE["groups"]:
        raise ValueError(f"Unknown reference group '{group}'.")

    params = REFERENCE["groups"][group]
    ages = np.arange(0.0, max_weeks + step, step)
    weights = gompertz(ages, params["A_g"], params["b"], params["k_per_week"])

    return {
        "group": group,
        "label": GROUP_LABELS[group],
        "model_version": MODEL_VERSION,
        "asymptote_g": params["A_g"],
        "b": params["b"],
        "k_per_week": params["k_per_week"],
        "source_citation": SOURCE_CITATION,
        "points": [
            {"age_weeks": round(float(a), 2), "reference_g": round(float(w), 1)}
            for a, w in zip(ages, weights)
        ],
    }
