"""add illness_checks table

Revision ID: 7bfb9f80640f
Revises: be64a9243d7b
Create Date: 2026-08-17 15:47:05.160384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7bfb9f80640f'
down_revision: Union[str, None] = 'be64a9243d7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('illness_checks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('rabbit_id', sa.UUID(), nullable=True),
    sa.Column('symptoms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('symptom_count', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("tier IN ('normal', 'monitor', 'see_vet_now')", name='ck_illness_checks_tier'),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_illness_checks_confidence_range'),
    sa.ForeignKeyConstraint(['rabbit_id'], ['rabbits.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_illness_checks_created_at'), 'illness_checks', ['created_at'], unique=False)
    op.create_index(op.f('ix_illness_checks_rabbit_id'), 'illness_checks', ['rabbit_id'], unique=False)
    op.create_index(op.f('ix_illness_checks_tier'), 'illness_checks', ['tier'], unique=False)
    op.create_index(op.f('ix_illness_checks_user_id'), 'illness_checks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_illness_checks_user_id'), table_name='illness_checks')
    op.drop_index(op.f('ix_illness_checks_tier'), table_name='illness_checks')
    op.drop_index(op.f('ix_illness_checks_rabbit_id'), table_name='illness_checks')
    op.drop_index(op.f('ix_illness_checks_created_at'), table_name='illness_checks')
    op.drop_table('illness_checks')
    # ### end Alembic commands ###
