"""add kit growth tracking tables

Revision ID: bd1e8d585f95
Revises: 7bfb9f80640f
Create Date: 2026-08-19 12:47:18.440995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd1e8d585f95'
down_revision: Union[str, None] = '7bfb9f80640f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kit_litters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('doe_id', sa.UUID(), nullable=True),
    sa.Column('kindling_date', sa.Date(), nullable=False),
    sa.Column('litter_size_born', sa.Integer(), nullable=True),
    sa.Column('litter_size_alive', sa.Integer(), nullable=True),
    sa.Column('housing_context', sa.String(length=20), server_default='unknown', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("housing_context IN ('individual', 'group', 'unknown')", name='ck_kit_litters_housing_context'),
    sa.CheckConstraint('litter_size_alive IS NULL OR litter_size_alive >= 0', name='ck_kit_litters_size_alive_nonneg'),
    sa.CheckConstraint('litter_size_born IS NULL OR litter_size_alive IS NULL OR litter_size_alive <= litter_size_born', name='ck_kit_litters_alive_le_born'),
    sa.CheckConstraint('litter_size_born IS NULL OR litter_size_born >= 0', name='ck_kit_litters_size_born_nonneg'),
    sa.ForeignKeyConstraint(['doe_id'], ['rabbits.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kit_litters_created_at'), 'kit_litters', ['created_at'], unique=False)
    op.create_index(op.f('ix_kit_litters_doe_id'), 'kit_litters', ['doe_id'], unique=False)
    op.create_index(op.f('ix_kit_litters_kindling_date'), 'kit_litters', ['kindling_date'], unique=False)
    op.create_index(op.f('ix_kit_litters_user_id'), 'kit_litters', ['user_id'], unique=False)
    op.create_table('kits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('litter_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('identifier', sa.String(length=50), nullable=False),
    sa.Column('sex', sa.String(length=10), server_default='unknown', nullable=False),
    sa.Column('status', sa.String(length=10), server_default='active', nullable=False),
    sa.Column('status_changed_on', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("sex IN ('unknown', 'male', 'female')", name='ck_kits_sex'),
    sa.CheckConstraint("status IN ('active', 'died', 'rehomed')", name='ck_kits_status'),
    sa.CheckConstraint('length(trim(identifier)) > 0', name='ck_kits_identifier_nonblank'),
    sa.ForeignKeyConstraint(['litter_id'], ['kit_litters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('litter_id', 'identifier', name='uq_kits_litter_identifier')
    )
    op.create_index(op.f('ix_kits_litter_id'), 'kits', ['litter_id'], unique=False)
    op.create_index(op.f('ix_kits_status'), 'kits', ['status'], unique=False)
    op.create_index(op.f('ix_kits_user_id'), 'kits', ['user_id'], unique=False)
    op.create_table('kit_weights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kit_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('measured_on', sa.Date(), nullable=False),
    sa.Column('weight_g', sa.Integer(), nullable=False),
    sa.Column('entry_source', sa.String(length=10), server_default='owner', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("entry_source IN ('owner', 'seed')", name='ck_kit_weights_entry_source'),
    sa.CheckConstraint('weight_g > 0 AND weight_g < 15000', name='ck_kit_weights_plausible_range'),
    sa.ForeignKeyConstraint(['kit_id'], ['kits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kit_id', 'measured_on', name='uq_kit_weights_kit_day')
    )
    op.create_index(op.f('ix_kit_weights_kit_id'), 'kit_weights', ['kit_id'], unique=False)
    op.create_index(op.f('ix_kit_weights_measured_on'), 'kit_weights', ['measured_on'], unique=False)
    op.create_index(op.f('ix_kit_weights_user_id'), 'kit_weights', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kit_weights_user_id'), table_name='kit_weights')
    op.drop_index(op.f('ix_kit_weights_measured_on'), table_name='kit_weights')
    op.drop_index(op.f('ix_kit_weights_kit_id'), table_name='kit_weights')
    op.drop_table('kit_weights')
    op.drop_index(op.f('ix_kits_user_id'), table_name='kits')
    op.drop_index(op.f('ix_kits_status'), table_name='kits')
    op.drop_index(op.f('ix_kits_litter_id'), table_name='kits')
    op.drop_table('kits')
    op.drop_index(op.f('ix_kit_litters_user_id'), table_name='kit_litters')
    op.drop_index(op.f('ix_kit_litters_kindling_date'), table_name='kit_litters')
    op.drop_index(op.f('ix_kit_litters_doe_id'), table_name='kit_litters')
    op.drop_index(op.f('ix_kit_litters_created_at'), table_name='kit_litters')
    op.drop_table('kit_litters')
    # ### end Alembic commands ###
